#!/usr/bin/env bash
# =============================================================================
# fleet-up.sh — bring up the portoser demo fleet (6 DinD "devices" + ~17
# popular homelab services + 3 custom node/python/go services).
#
# Idempotent. Safe to re-run; existing keys, host containers, and SSH config
# entries are detected and reused.
#
# Order of operations:
#   1. Preflight (docker, the web stack must be up).
#   2. Generate the demo SSH key under demo/fleet/keys/ if absent.
#   3. Wire that key into the operator's ~/.ssh/{config,portoser_demo*}.
#   4. Build fakehost image + 3 custom service images on the operator daemon.
#   5. `docker compose up -d` the fleet (demo-mirror + 6 fakehosts).
#   6. Wait for sshd on every fakehost.
#   7. Push the 3 custom images into the fakehosts that need them, via
#      `docker save | docker exec -i <host> docker load`.
#   8. Re-trigger each fakehost's seed compose so the now-loaded custom
#      images come up alongside the public ones.
#   9. Swap demo/fleet/registry.demo-cluster.yml into web/registry/registry.yml
#      and ask portoser-api to reload.
#  10. Print URLs.
# =============================================================================
set -euo pipefail

# ----------------------------------------------------------------------------
# Paths & UI
# ----------------------------------------------------------------------------
FLEET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$FLEET_DIR/../.." && pwd)"
WEB_DIR="$REPO_ROOT/web"

GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'; RED=$'\033[0;31m'; NC=$'\033[0m'
step() { printf "${BLUE}==>${NC} %s\n" "$1"; }
ok()   { printf "${GREEN}✓${NC}  %s\n" "$1"; }
warn() { printf "${YELLOW}!! ${NC}%s\n" "$1" >&2; }
die()  { printf "${RED}✗  %s${NC}\n" "$1" >&2; exit 1; }

# Hosts in the fleet, and which custom image each one needs (empty = none).
# Indexed-array pair, keyed by position.
HOSTS=(mac-mini desktop-pc raspi-4 synology-nas framework-laptop intel-nuc)
HOST_IMG=(""    go-fileserver python-sensors node-recipes  ""               "")

# ----------------------------------------------------------------------------
# 1. Preflight
# ----------------------------------------------------------------------------
step "Preflight"
command -v docker >/dev/null || die "docker not on PATH"
docker info >/dev/null 2>&1 || die "docker daemon not reachable (is Docker Desktop running?)"

if ! docker network inspect workflow-system-network >/dev/null 2>&1; then
    die "workflow-system-network not found — run web/dev-up.sh first to bring up the web stack"
fi
if ! docker inspect -f '{{.State.Status}}' portoser-api 2>/dev/null | grep -q running; then
    die "portoser-api container not running — run web/dev-up.sh first"
fi
ok "web stack is up"

# ----------------------------------------------------------------------------
# 2. Demo SSH keypair
# ----------------------------------------------------------------------------
step "SSH keypair (demo/fleet/keys/portoser_demo)"
KEY_DIR="$FLEET_DIR/keys"
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"
if [ ! -f "$KEY_DIR/portoser_demo" ]; then
    ssh-keygen -t ed25519 -N "" -C "portoser-demo-fleet" -f "$KEY_DIR/portoser_demo" >/dev/null
    ok "generated $KEY_DIR/portoser_demo"
else
    ok "key exists, reusing"
fi
chmod 600 "$KEY_DIR/portoser_demo"
chmod 644 "$KEY_DIR/portoser_demo.pub"

# ----------------------------------------------------------------------------
# 3. Operator's ~/.ssh: key + config snippet so portoser-api (which mounts
#    ~/.ssh:ro) sees the right IdentityFile for our demo hostnames.
# ----------------------------------------------------------------------------
step "Operator ~/.ssh wiring"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

# Copy the private key into ~/.ssh so the bind mount in web/docker-compose.yml
# (~/.ssh -> /root/.ssh) makes it visible inside portoser-api.
cp -f "$KEY_DIR/portoser_demo" "$HOME/.ssh/portoser_demo"
cp -f "$KEY_DIR/portoser_demo.pub" "$HOME/.ssh/portoser_demo.pub"
chmod 600 "$HOME/.ssh/portoser_demo"
chmod 644 "$HOME/.ssh/portoser_demo.pub"

CONF_FILE="$HOME/.ssh/portoser_demo.config"
cat > "$CONF_FILE" <<EOF
# Generated by demo/fleet/fleet-up.sh — remove with demo/fleet/fleet-down.sh.
# Both the bare hostnames and the static IPs match here, because portoser's
# bash lib uses ssh_hostname (e.g. "mac-mini") for some calls and the raw
# 'ip:' field (e.g. "172.18.99.10") for others. The pattern matches both so
# either path picks up the demo IdentityFile.
Host mac-mini desktop-pc raspi-4 synology-nas framework-laptop intel-nuc 172.18.99.10 172.18.99.20 172.18.99.30 172.18.99.40 172.18.99.50 172.18.99.60
    User portoser
    IdentityFile ~/.ssh/portoser_demo
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
    ConnectTimeout 10
EOF
chmod 600 "$CONF_FILE"
ok "wrote $CONF_FILE"

INCLUDE_LINE="Include ~/.ssh/portoser_demo.config"
SSH_CFG="$HOME/.ssh/config"
touch "$SSH_CFG"
chmod 600 "$SSH_CFG"
if ! grep -qxF "$INCLUDE_LINE" "$SSH_CFG"; then
    # Prepend so it wins over any later `Host *` blocks.
    tmp=$(mktemp)
    printf '%s\n\n' "$INCLUDE_LINE" > "$tmp"
    cat "$SSH_CFG" >> "$tmp"
    mv "$tmp" "$SSH_CFG"
    chmod 600 "$SSH_CFG"
    ok "added Include directive to $SSH_CFG"
else
    ok "Include directive already present"
fi

# ----------------------------------------------------------------------------
# 4. Build images on operator daemon
# ----------------------------------------------------------------------------
step "Build fakehost image"
docker build -q -t portoser-fakehost:latest "$FLEET_DIR/fakehost" >/dev/null
ok "portoser-fakehost:latest"

step "Build custom service images (node-recipes, python-sensors, go-fileserver)"
for svc in node-recipes python-sensors go-fileserver; do
    docker build -q -t "portoser-demo/$svc:latest" "$FLEET_DIR/custom-services/$svc" >/dev/null
    ok "portoser-demo/$svc:latest"
done

# ----------------------------------------------------------------------------
# 5. Compose up
# ----------------------------------------------------------------------------
step "docker compose up -d (demo-mirror + 6 fakehosts)"
docker compose -f "$FLEET_DIR/compose.fleet.yml" --project-directory "$FLEET_DIR" up -d
ok "fleet containers started"

# ----------------------------------------------------------------------------
# 6. Wait for sshd on each fakehost (probed via portoser-api's nc, which
#    proves the SAME path the lib uses for healthchecks works.)
# ----------------------------------------------------------------------------
step "Waiting for sshd on every fakehost"
deadline=$(( $(date +%s) + 180 ))
for host in "${HOSTS[@]}"; do
    while true; do
        if docker exec portoser-api nc -z -w 2 "$host" 22 >/dev/null 2>&1; then
            ok "$host:22"
            break
        fi
        if [ "$(date +%s)" -gt "$deadline" ]; then
            docker logs --tail 30 "host-$host" >&2 || true
            die "$host:22 never opened (3min timeout)"
        fi
        sleep 2
    done
done

# ----------------------------------------------------------------------------
# 7. Push custom images into the fakehosts that need them
# ----------------------------------------------------------------------------
step "Loading custom images into fakehosts that use them"
for i in "${!HOSTS[@]}"; do
    img=${HOST_IMG[$i]}
    [ -z "$img" ] && continue
    host=${HOSTS[$i]}
    # Stream the tarball straight from operator's daemon into the fakehost's
    # daemon via the container's docker CLI. No registry, no SSH, no temp files.
    docker save "portoser-demo/$img:latest" \
      | docker exec -i "host-$host" docker load >/dev/null
    ok "$img:latest -> host-$host"
done

# ----------------------------------------------------------------------------
# 8. Re-trigger each fakehost's seed compose now that its custom images exist.
#    The first attempt at boot may have partially failed for hosts referencing
#    not-yet-loaded images; this is the deterministic second pass.
# ----------------------------------------------------------------------------
step "Reconciling per-host services"
for host in "${HOSTS[@]}"; do
    if docker exec "host-$host" docker compose -f /srv/services.yml up -d --quiet-pull >/dev/null 2>&1; then
        ok "host-$host services up"
    else
        warn "host-$host: 'docker compose up' returned non-zero (some images still pulling? re-run fleet-up.sh)"
    fi
done

# ----------------------------------------------------------------------------
# 8a. Bootstrap each fakehost so portoser's metrics CLI can SSH in and source
#     ~/.portoser_lib/{platform,metrics,...}/. The CLI's own
#     `portoser remote bootstrap` command currently fails its `validate_path`
#     check on `~/.portoser_lib`, so we do the equivalent ourselves: install
#     bash + jq + coreutils (alpine fakehosts), pre-create the dirs, tar-pipe
#     the lib subtrees in. Without this, /api/metrics/<svc>/<machine> returns
#     "metrics_unavailable" everywhere.
# ----------------------------------------------------------------------------
step "Bootstrapping fakehost metrics libs (~/.portoser_lib/)"
LIB_SUBTREES=(metrics platform observe diagnose solve standardize history dependencies health utils)
for host in "${HOSTS[@]}"; do
    docker exec "host-$host" sh -c 'apk add --no-cache bash jq coreutils >/dev/null 2>&1' || true
    docker exec portoser-api ssh -o StrictHostKeyChecking=no -o BatchMode=yes "portoser@$host" \
        "mkdir -p ~/.portoser_lib && for d in ${LIB_SUBTREES[*]}; do mkdir -p ~/.portoser_lib/\$d; done"
    tar -C "$REPO_ROOT/lib" -cf - "${LIB_SUBTREES[@]}" 2>/dev/null \
      | docker exec -i portoser-api ssh -o StrictHostKeyChecking=no -o BatchMode=yes "portoser@$host" \
            'tar -xf - -C ~/.portoser_lib' \
      && ok "$host: libs synced"
done

# ----------------------------------------------------------------------------
# 9. Swap the demo registry into web/registry/registry.yml so portoser-api
#    sees the demo cluster instead of the example/dev registry.
# ----------------------------------------------------------------------------
step "Pointing portoser-api at the demo registry"
mkdir -p "$WEB_DIR/registry"
if [ -f "$WEB_DIR/registry/registry.yml" ] && ! [ -f "$WEB_DIR/registry/registry.yml.pre-fleet.bak" ]; then
    cp "$WEB_DIR/registry/registry.yml" "$WEB_DIR/registry/registry.yml.pre-fleet.bak"
    ok "backed up existing registry.yml -> registry.yml.pre-fleet.bak"
fi
cp "$FLEET_DIR/registry.demo-cluster.yml" "$WEB_DIR/registry/registry.yml"
ok "wrote demo registry"

# ----------------------------------------------------------------------------
# 9a. Seed believable demo data under demo/fleet/state/portoser_home/.
#     This becomes the PORTOSER_HOME bind-mount source for portoser-api so the
#     /api/history, /api/knowledge, and /api/metrics/<svc>/<m>/history endpoints
#     all return populated content instead of "no data" placeholders.
# ----------------------------------------------------------------------------
step "Seeding demo data (deployments, knowledge, metrics history)"
PORTOSER_HOME_DEMO="$FLEET_DIR/state/portoser_home"
python3 "$FLEET_DIR/seed-data.py" --portoser-home "$PORTOSER_HOME_DEMO" 2>&1 | sed 's/^/    /'

# Bring the web stack back up with PORTOSER_HOME pointed at our demo state so
# the docker-compose.yml mounts pick up the seeded content.
step "Restarting portoser-api with PORTOSER_HOME → demo state"
PORTOSER_HOME="$PORTOSER_HOME_DEMO" docker compose \
    -f "$WEB_DIR/docker-compose.yml" --project-directory "$WEB_DIR" \
    up -d portoser >/dev/null
ok "compose up portoser (PORTOSER_HOME=$PORTOSER_HOME_DEMO)"

# Wait for backend to be healthy again
deadline=$(( $(date +%s) + 60 ))
while ! curl -sf -m 3 http://localhost:8988/ping >/dev/null 2>&1; do
    [ "$(date +%s)" -gt "$deadline" ] && die "portoser-api never came back up"
    sleep 1
done
ok "portoser-api back to healthy"

# ----------------------------------------------------------------------------
# 10. Banner
# ----------------------------------------------------------------------------
cat <<BANNER

${GREEN}====================================================${NC}
${GREEN}  Portoser demo fleet — up                          ${NC}
${GREEN}====================================================${NC}

  ${BLUE}UI            ${NC} http://localhost:8989
  ${BLUE}Backend       ${NC} http://localhost:8988
  ${BLUE}Hosts         ${NC} mac-mini · desktop-pc · raspi-4 · synology-nas · framework-laptop · intel-nuc

  Verify SSH path used by the orchestration lib:
    docker exec portoser-api ssh -o StrictHostKeyChecking=no portoser@mac-mini 'docker ps'

  ${YELLOW}Tear down:${NC}  demo/fleet/fleet-down.sh
BANNER
