#!/usr/bin/env bash
# Quick start script for Portoser Web Interface

set -euo pipefail

# Trap to cleanup background processes on exit
trap 'kill $(jobs -p) 2>/dev/null' EXIT INT TERM

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Portoser Web Interface - Quick Start${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if backend and frontend directories exist
if [ ! -d "backend" ] || [ ! -d "frontend" ]; then
    echo -e "${YELLOW}Error: backend or frontend directory not found${NC}"
    exit 1
fi

# Start backend
echo -e "${GREEN}Starting backend...${NC}"
cd backend

if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv venv
fi

# shellcheck source=/dev/null  # generated by python -m venv at runtime
source venv/bin/activate
pip install -q -r requirements.txt

echo -e "${GREEN}Backend starting on http://localhost:8988${NC}"
python main.py &
BACKEND_PID=$!

cd ..

# Start frontend
echo -e "${GREEN}Starting frontend...${NC}"
cd frontend

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    npm install
fi

echo -e "${GREEN}Frontend starting on http://localhost:8989${NC}"
npm run dev &
FRONTEND_PID=$!

cd ..

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Portoser Web Interface is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Backend:  ${BLUE}http://localhost:8988${NC}"
echo -e "Frontend: ${BLUE}http://localhost:8989${NC}"
echo -e "API Docs: ${BLUE}http://localhost:8988/docs${NC}"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop both servers${NC}"
echo ""

# Trap Ctrl+C to stop both processes
cleanup() {
    echo ''
    echo 'Stopping servers...'
    # Verify PIDs exist before killing
    [ -n "$BACKEND_PID" ] && ps -p "$BACKEND_PID" >/dev/null 2>&1 && kill "$BACKEND_PID" 2>/dev/null
    [ -n "$FRONTEND_PID" ] && ps -p "$FRONTEND_PID" >/dev/null 2>&1 && kill "$FRONTEND_PID" 2>/dev/null
    wait 2>/dev/null || true
    exit
}
trap cleanup INT TERM

# Wait for processes
wait
